#!/bin/zsh

killall conky
sleep 10s

conky -dq -c ~/.conky/cards/time_rc
conky -dq -c ~/.conky/cards/system_rc
conky -dq -c ~/.conky/cards/processes_rc
conky -dq -c ~/.conky/cards/memory_rc
conky -dq -c ~/.conky/cards/filesystem_rc
conky -dq -c ~/.conky/cards/network_rc
conky -dq -c ~/.conky/cards/servers_rc
conky -dq -c ~/.conky/cards/news_rc
conky -dq -c ~/.conky/cards/backup_rc

